// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCndfwNOrRNo6wRhgCQ86bUawURxOgAy2o',
    appId: '1:1032004674679:web:acca9a3951771d3f095272',
    messagingSenderId: '1032004674679',
    projectId: 'v-shape-gym',
    authDomain: 'v-shape-gym.firebaseapp.com',
    storageBucket: 'v-shape-gym.firebasestorage.app',
    measurementId: 'G-KVBTV0RGGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt31J4ig1ppQsgb9Vtf2a8L6W3kMyQuls',
    appId: '1:1032004674679:android:a6d3527333cee405095272',
    messagingSenderId: '1032004674679',
    projectId: 'v-shape-gym',
    storageBucket: 'v-shape-gym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkXw9gthkmWTBvbjZYO66axaWirKN4NqY',
    appId: '1:1032004674679:ios:4c100cbae51db689095272',
    messagingSenderId: '1032004674679',
    projectId: 'v-shape-gym',
    storageBucket: 'v-shape-gym.firebasestorage.app',
    iosBundleId: 'com.example.vShapeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkXw9gthkmWTBvbjZYO66axaWirKN4NqY',
    appId: '1:1032004674679:ios:4c100cbae51db689095272',
    messagingSenderId: '1032004674679',
    projectId: 'v-shape-gym',
    storageBucket: 'v-shape-gym.firebasestorage.app',
    iosBundleId: 'com.example.vShapeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCndfwNOrRNo6wRhgCQ86bUawURxOgAy2o',
    appId: '1:1032004674679:web:aec031acd0b3a89c095272',
    messagingSenderId: '1032004674679',
    projectId: 'v-shape-gym',
    authDomain: 'v-shape-gym.firebaseapp.com',
    storageBucket: 'v-shape-gym.firebasestorage.app',
    measurementId: 'G-WN5M43319J',
  );
}
